development:
  db_hosts: [localhost]
  db_port: 9042
  db_username: ''
  db_password: ''
  db_keyspace: xadf

  kafka_broker_hosts: ['localhost:9092']
  kafka_client: xadf_schedule

production:
  db_hosts: [localhost]
  db_port: 9042
  db_username: ''
  db_password: ''
  db_keyspace: xadf

  kafka_broker_hosts: ['localhost:9092']
  kafka_client: xadf_schedule