development:
  mongo:
    url: 'mongodb://127.0.0.1:27017/xadf'

  kafka:
    broker_hosts: ['localhost:9092']
    client: xadf_schedule

  cassandra:
    hosts: [localhost]
    username: ''
    password: ''
    keyspace: xadf

production:
  mongo:
    url: 'mongodb://mongodb.marathon.l4lb.thisdcos.directory:27017'
    
  kafka:
    broker_hosts: ['localhost:9092']
    client: xadf_schedule

  cassandra:
    hosts: [node-0-server.cassandra.autoip.dcos.thisdcos.directory, node-1-server.cassandra.autoip.dcos.thisdcos.directory]
    username: ''
    password: ''
    keyspace: xadf
