development:
  arango:
    host: localhost
    port: 8529
    username: ''
    password: ''
    name: 'xadf'

  kafka:
    broker_hosts: ['localhost:9092']
    client: xadf_schedule

production:
  arango:
    host: localhost
    port: 8529
    username: ''
    password: ''
    name: 'xadf'

  kafka:
    broker_hosts: ['localhost:9092']
    client: xadf_schedule
