development:
  mongo:
    url: 'mongodb://127.0.0.1:27017/xadf'

  kafka:
    broker_hosts: ['localhost:9092']
    client: xadf_schedule

production:
  mongo:
    url: 'mongodb://127.0.0.1:27017/xadf'
    
  kafka:
    broker_hosts: ['localhost:9092']
    client: xadf_schedule
