FROM ruby:2.4.2-alpine

RUN bundle config --global frozen 1

RUN mkdir -p /app
WORKDIR /app

COPY Gemfile /app
COPY Gemfile.lock /app

RUN apk --no-cache add cmake make gcc g++ libc-dev linux-headers
RUN bundle install --without test development

COPY . /app

RUN apk del cmake make gcc g++ libc-dev linux-headers
